server:
  port: 8046

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myfirst?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:com/tony/imagelink/mapper/*.xml
  type-aliases-package: com.tony.imagelink.mapper.entity.*
  config-location: classpath:mybatis-config.xml
jpa:
  show-sql: true //数据库语句打印出来
logging:
  config: classpath:logback-spring.xml