server:
  port: 8046

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myfirst?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 3
    maxActive: 10
    minIdle: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT now()
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j

mybatis:
  mapper-locations: classpath*:com/tony/imagelink/mapper/*Mapper.xml
  type-aliases-package: com.tony.imagelink.mapper.entity
  config-location: classpath:mybatis-config.xml
jpa:
  show-sql: true //数据库语句打印出来

logging:
  config: classpath:logback-spring.xml